remote_theme: jekyll-theme-cayman
title: coucou estelle
description: rADAdouille 
show_downloads: True
navigation:
  - title: example.md
    url: example.md
  - title: new_one.md
    url: new_one.md

